export const CAHNGE_TOP_BANNERS = 'CAHNGE_TOP_BANNERS';
export const CHANGE_HOT_RECOMMENDS = 'CHANGE_HOT_RECOMMENDS';
export const CHANGE_NEW_ALBUMS = 'CHANGE_NEW_ALBUMS';

export const CHANGE_RANKINGS = 'CHANGE_RANKINGS';
export const CHANGE_S_RANKINGS = 'CHANGE_S_RANKINGS';
export const CHANGE_N_RANKINGS = 'CHANGE_N_RANKINGS';
export const CHANGE_O_RANKINGS = 'CHANGE_O_RANKINGS';
export const CHANGE_C_RANKINGS = 'CHANGE_C_RANKINGS';

export const CHANGE_MUSICIAN = 'CHANGE_MUSICIAN';
export const CHANGE_ANCHOR = 'CHANGE_ANCHOR';

